apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender-deploy
  namespace: istio-demo-tx
spec:
  selector:
    matchLabels:
      app: sender-app
  replicas: 1
  template:
    metadata:
      labels:
        app: sender-app
    spec:
      containers:
        - name: sender-app
          image: ${SENDER_IMAGE}
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
      imagePullSecrets:
        - name: dockerhub-secret
