apiVersion: v1
kind: Service
metadata:
  name: sender-svc
  namespace: istio-demo-tx
spec:
  selector:
    app: sender-app
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
