apiVersion: v1
kind: Service
metadata:
  name: php-svc
spec:
  selector:
    app: php-server
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30420
