#!/usr/bin/env bash
remote="$1"
url="$2"

zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')

while read local_ref local_oid remote_ref remote_oid
do
  if test "$local_oid" != "$zero"; then
    echo "Running git hook pre-push"
    # Add your pre-push git hook here
  fi
done
