apiVersion: v1
kind: Service
metadata:
  name: receiver-svc
  namespace: istio-demo-rx
spec:
  selector:
    app: receiver-app
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
