---
version: "3.5"
services:
  nginx:
    image: nginx:1.21.3
    ports:
      - 8080:80
    volumes:
      - ./html:/usr/share/nginx/html/
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
