- name: Install httpd, git and vim
  hosts: all
  roles:
    - role: httpd
      become: yes
    - role: git
      become: yes
    - role: vim

- name: Hardens sshd config
  hosts: all
  roles:
    - role: sshd_setup
